<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\STC.Shared\src\Utilities\STC.Shared.Logger\STC.Shared.Logger.csproj" />
      <ProjectReference Include="..\..\Core\STC.Auth.Application\STC.Auth.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    </ItemGroup>

</Project>
